### ISSUE TITLE
Brewing Mana Regeneration potions creates the wrong potion

### ISSUE THREAD

**Issue by Gruer** [SimonMeskens/Shenanigazam#42]
When trying to brew extended (8 minute duration) Mana regeneration potions. It creates Potion of sliding extended potions instead. The recipie on JEI is correct which is adding redstone to a potion of mana regeneration.  I have not tried to input the ingredients manually. This was hopper fed.

**Comment by SimonMeskens** [comment]
Should be fixed in next update, was a recipe conflict
